// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZWOGz7PkUBDmzsm-PaGKwxdOiF_D0pvQ',
    appId: '1:675894876550:web:0ddd7b644ba7189cfe3407',
    messagingSenderId: '675894876550',
    projectId: 'loanapp-d949a',
    authDomain: 'loanapp-d949a.firebaseapp.com',
    storageBucket: 'loanapp-d949a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwWc2mr0yMp5CmNIpodUirY50Bmh5jMMY',
    appId: '1:675894876550:android:0e9aa052ba974e83fe3407',
    messagingSenderId: '675894876550',
    projectId: 'loanapp-d949a',
    storageBucket: 'loanapp-d949a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaUgUMhHLjda8YeeZkSzwGXiuEnrt0CZw',
    appId: '1:675894876550:ios:84941d553e7e00cefe3407',
    messagingSenderId: '675894876550',
    projectId: 'loanapp-d949a',
    storageBucket: 'loanapp-d949a.firebasestorage.app',
    iosBundleId: 'com.example.loanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaUgUMhHLjda8YeeZkSzwGXiuEnrt0CZw',
    appId: '1:675894876550:ios:84941d553e7e00cefe3407',
    messagingSenderId: '675894876550',
    projectId: 'loanapp-d949a',
    storageBucket: 'loanapp-d949a.firebasestorage.app',
    iosBundleId: 'com.example.loanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZWOGz7PkUBDmzsm-PaGKwxdOiF_D0pvQ',
    appId: '1:675894876550:web:2247a898c1c80ec3fe3407',
    messagingSenderId: '675894876550',
    projectId: 'loanapp-d949a',
    authDomain: 'loanapp-d949a.firebaseapp.com',
    storageBucket: 'loanapp-d949a.firebasestorage.app',
  );
}
